# Traefik Configuration for Kubernetes Gateway API
# Optimized for AWS EKS with NLB integration
# Compatible with EKS cluster version 1.32 and Traefik v3.2

########################################################################################################################
# Global Configuration
########################################################################################################################
global:
  # Disable sending anonymous usage statistics
  sendAnonymousUsage: false

########################################################################################################################
# Image Configuration
########################################################################################################################
image:
  # Use official Traefik image
  registry: docker.io
  repository: traefik
  tag: "v3.4.1"
  pullPolicy: IfNotPresent

########################################################################################################################
# Deployment Configuration
########################################################################################################################
deployment:
  enabled: true
  kind: Deployment
  replicas: 1
  minReadySeconds: 10
  
  # Pod disruption budget for high availability
  podDisruptionBudget:
    enabled: false
    maxUnavailable: 1

  # Rolling update strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

########################################################################################################################
# Pod Configuration
########################################################################################################################
# Security context for enhanced security
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE
  readOnlyRootFilesystem: true

########################################################################################################################
# RBAC Configuration
########################################################################################################################
rbac:
  enabled: true

########################################################################################################################
# Traefik Configuration
########################################################################################################################
# Static configuration
additionalArguments:
  # Gateway API Provider Configuration
  - "--providers.kubernetesgateway"
  - "--providers.kubernetesgateway.experimentalChannel=true"
  - "--providers.kubernetesgateway.throttleDuration=2s"
  
  # Certificate Resolvers (commented out - using ACM instead)
  # - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
  # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
  # - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  
  # Metrics and monitoring
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
  - "--entrypoints.metrics.address=:8080"
  
  # API and dashboard
  - "--api.dashboard=true"
  - "--api.insecure=false"
  
  # Global HTTP to HTTPS redirect
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
  
  # Health checks
  - "--ping=true"
  - "--ping.entrypoint=traefik"

########################################################################################################################
# Ports Configuration
########################################################################################################################
ports:
  traefik:
    port: 9000
    expose:
      default: false
    exposedPort: 9000
    protocol: TCP
  
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
    healthchecksPort: 8080
    # HTTP to HTTPS redirect handled via additionalArguments
  
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    healthchecksPort: 8080
    tls:
      enabled: true
      options: ""
      certResolver: "letsencrypt"
  
  metrics:
    port: 8080
    expose:
      default: false
    exposedPort: 8080
    protocol: TCP

########################################################################################################################
# Service Configuration for NLB
########################################################################################################################
service:
  enabled: true
  single: true
  type: LoadBalancer
  
  # NLB-specific annotations
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
  
  # Service labels
  labels: {}
  
  # Load balancer configuration
  spec:
    externalTrafficPolicy: Local
    loadBalancerSourceRanges: []
  
  # Health check configuration
  loadBalancerHealthCheckGracePeriodSeconds: 60

########################################################################################################################
# Persistence Configuration (Disabled - using ACM certificates)
########################################################################################################################
persistence:
  enabled: false

########################################################################################################################
# Resource Configuration
########################################################################################################################
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

########################################################################################################################
# Autoscaling Configuration
########################################################################################################################
autoscaling:
  enabled: false  # Disabled in favor of fixed replicas for testing
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

########################################################################################################################
# Health Checks Configuration
########################################################################################################################
readinessProbe:
  failureThreshold: 1
  initialDelaySeconds: 2
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 2
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2

########################################################################################################################
# Logs Configuration
########################################################################################################################
logs:
  general:
    level: DEBUG
    filePath: ""
  access:
    enabled: true
    filePath: ""
    format: json
    bufferingSize: 100

########################################################################################################################
# Metrics Configuration
########################################################################################################################
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    buckets: "0.1,0.3,1.2,5.0"
    disableAPICheck: false

########################################################################################################################
# TLS Configuration
########################################################################################################################
tlsOptions:
  default:
    minVersion: "VersionTLS12"
    maxVersion: "VersionTLS13"
    cipherSuites:
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

########################################################################################################################
# Node Selector and Affinity
########################################################################################################################
nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - traefik
          topologyKey: kubernetes.io/hostname

########################################################################################################################
# Environment Variables
########################################################################################################################
env:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace

########################################################################################################################
# Additional Volumes and Volume Mounts (used for ACM certificates; Disabled)
########################################################################################################################
# volumes:
#   - name: tmp
#     emptyDir: {}
#   - name: plugins-storage
#     emptyDir: {}

# volumeMounts:
#   - name: tmp
#     mountPath: /tmp
#   - name: plugins-storage
#     mountPath: /plugins-storage

########################################################################################################################
# Experimental Features
########################################################################################################################
experimental:
  kubernetesGateway:
    enabled: true

########################################################################################################################
# Hub Configuration (Traefik Hub integration)
########################################################################################################################
hub:
  enabled: false

########################################################################################################################
# Additional Labels
########################################################################################################################
commonLabels:
  app.kubernetes.io/component: "ingress-controller"
  app.kubernetes.io/part-of: "traefik"

########################################################################################################################
# Priority Class
########################################################################################################################
priorityClassName: "system-cluster-critical"
